### ISSUE TITLE
XML woes

### ISSUE THREAD

**Issue by sdwfrost** [PoonLab/sierra-local#42] opened 2018-09-11 17:50 UTC
Hi @ArtPoon 

I'm trying to run sierra-local, but I get errors if I don't include an XML:

```sh
Error: could not retrieve HIVDB XML
Unable to update HIVDB XML. Try manually downloading the HIVdb ASI2.
Traceback (most recent call last):
  File "/usr/local/bin/sierralocal", line 11, in <module>
    exit_code = main.main()
  File "/usr/local/lib/python3.5/dist-packages/sierralocal/main.py", line 157, in main
    count, time_elapsed = sierralocal(args.fasta, args.outfile, args.xml, args.skipalign, args.forceupdate)
  File "/usr/local/lib/python3.5/dist-packages/sierralocal/main.py", line 111, in sierralocal
    algorithm = HIVdb(path=xml, forceupdate=forceupdate)
  File "/usr/local/lib/python3.5/dist-packages/sierralocal/hivdb.py", line 58, in __init__
    if not os.path.isfile(Path(os.path.dirname(__file__))/'data'/'apobec.tsv'):
  File "/usr/lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: argument should be string, bytes or integer, not PosixPath
```

while including the HIVdb XML gives the following error

```sh
Traceback (most recent call last):
  File "/usr/local/bin/sierralocal", line 11, in <module>
    exit_code = main.main()
  File "/usr/local/lib/python3.5/dist-packages/sierralocal/main.py", line 157, in main
    count, time_elapsed = sierralocal(args.fasta, args.outfile, args.xml, args.skipalign, args.forceupdate)
  File "/usr/local/lib/python3.5/dist-packages/sierralocal/main.py", line 111, in sierralocal
    algorithm = HIVdb(path=xml, forceupdate=forceupdate)
  File "/usr/local/lib/python3.5/dist-packages/sierralocal/hivdb.py", line 58, in __init__
    if not os.path.isfile(Path(os.path.dirname(__file__))/'data'/'apobec.tsv'):
  File "/usr/lib/python3.5/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: argument should be string, bytes or integer, not PosixPath
```

**Comment by ArtPoon** [comment] 2018-09-11 17:56
Hi @sdwfrost, did you try to install sierra-local via pip3?  Unfortunately that package is broken, and is not retrieving the required XML files from the Stanford site because the destination folder doesn't exist.  I would recommend cloning the repo off the master branch and running `sudo python3 setup.py install`, followed by calling `sierralocal` to download the XMLs and running again.  I have made several fixes since the pip3 version.  Please let me know how it goes and sorry for the inconvenience.

**Comment by sdwfrost** [comment] 2018-09-11 18:26
I installed from the git repository, trying both pip and distutils - not a great idea, as I have to downgrade to pip 9.0.3 in order to uninstall distutils packages. Doesn't work, but could well be due to the Python spaghetti on my machine.

**Comment by ArtPoon** [comment] 2018-09-11 18:39
Can you please tell me what OS you're running, Python version etc so I can reproduce the issue?  Also, what method of distribution would you recommend?  I'm rather weak on packaging...

**Comment by sdwfrost** [comment] 2018-09-11 18:42
I'm running Ubuntu 16.04, with the system Python (3.5). I can set up a Docker container if that helps. I haven't put anything on pypi, so I'm probably not much help in the packaging department.

**Comment by ArtPoon** [comment] 2018-09-11 18:45
Thanks.  I'll expand on open issue #35 with this and get back to you as soon as I can.

**Comment by ArtPoon** [comment] 2018-09-11 18:55
Ok, reproduced on my laptop running elementaryOS (Ubuntu 16.04) with Python 3.5.2.  Looking into it.

**Comment by ArtPoon** [comment] 2018-09-12 12:42
Ok the first problem is that Python 3.5 doesn't support `open` for `PosixPath` objects.  We've been doing our development and testing with Python 3.6.  Fixing in next commit.

The other problem is that Python is attempting to write the downloaded XML into `/usr/local/lib/python3.5/dist-packages/sierralocal.data`, which has permissions set to `drwxr-sr-x` by default.  I forgot that we manually switched this with a `chmod 777`, which is hardly elegant.  Looking around for some way to get this working out of the box.

**Comment by ArtPoon** [comment] 2018-09-12 20:35
* Lots of substitutions of `str(PosixPath)` throughout code needed to support Python 3.5
* Modified `setup.py` to set folder permissions on `/data` to `777`.
* User is required to download `nucamino` as a dependency and set the file permissions to r+x.  This won't change unless we start distributing the binary in our repo, which is permitted under their MIT license.
* Might need to update installation instructions.

**Comment by ArtPoon** [comment] 2018-09-12 20:50
Ok @sdwfrost could I please trouble you to pull the current master branch (commit 599abd7) and do the following:
* run `sudo python3 setup.py install`
* download the `nucamino-linux64` binary from http://github.com/hivdb/nucamino/releases
* set user permissions on the binary to `755`
* copy the binary to `/usr/local/lib/python3.5/dist-packages/sierralocal`
* try running `sierralocal` on some test data
thanks!

**Comment by sdwfrost** [comment] 2018-09-12 21:16
This looks as though it fixes the problem. Is there any reason to include NucAmino in sierralocal rather than just having something in the path? For the XML, is there any reason *not* to include in the package?

**Comment by ArtPoon** [comment] 2018-09-12 21:58
Yeah I was just thinking about this on the way home.  
* I'm inclined not to package NucAmino with sierralocal because of needing to handle different binaries
* I agree that it might be slightly easier (from the user perspective) to "install" NucAmino in one's PATH, rather than copy it into the Python package dir.  I'll look into this for a (near) future release.
* I decided to not include the XML files because they are not released under any license that I could find.  In addition, I feel that bundling a particular set of XML files in the repo might be interpreted as certifying that version as the "best" one; I would rather leave such decisions up to the user. 

As the problem is fixed (for now), I'm closing the issue.  Thanks for the feedback!

**Closed by ArtPoon** 2018-09-12 21:58 UTC

**Comment by sdwfrost** [comment] 2018-09-13 20:54
Some feedback:

- Agreed that it's a pain to include binaries. Even using git submodules isn't great, as NucAmino requires Go to compile, so you'd need to have that toolchain in addition to Python. One of the reasons I prefer BioExt alignment (which is also faster and more customisable), but I appreciate you're trying to be 100% consistent with sierra.
- Perhaps you could include a helper script to download all the XML files into a user-specified directory? I don't like the tinkering with permissions.

**Comment by ArtPoon** [comment] 2018-09-13 22:06
On the second point - it is possible to run sierralocal in a local user filesystem, *i.e.*, without admin privileges so I believe that would be similar to what you propose.  Currently the main driver script allows the user to specify a path to a particular XML file, which is handy for running the same sequences under different versions of the ASI.  I think if we provide another cmdline option to specify the location of a NucAmino binary, we are pretty much there.
