### ISSUE TITLE
Polymorphism interpretation

### ISSUE THREAD

**Issue by jzpero** [PoonLab/sierra-local#14] opened 2017-12-15 23:33 UTC
I've tracked down most of the bugs and errors. Currently sierra-local can process 97-100% of a large sample size verified against sierrapy. However, the main issue seems to be with polymorphic variations.

Example:
Nucamino returns this mutation list for 71-1.Cameroon :
> [...], Q95KNRSQH:MRK, [...]

I interpret this currently as Q at residue 95 -> any one of KNRSQH. However, sierrapy interprets this as Q95X. This causes me to wrongfully add a score if any of Q95KNRSQH are associated with a drug resistance. In other cases, sierrapy interprets polymorphisms in the way I currently do, and there are no issues there.

_Is there a standard way to determine when an amino acid is considered "unknown--X" vs just a list of polymorphisms?_

There's also an issue with sierrapy choosing some polymorphisms over others.
Let's say a sequence has the mutation V82TA:RCC. Sierrapy sometimes chooses to exclude the score for V82T alone, and other times uses either V82A or V82T in its scoring. I'm not exactly sure how they determine this. Will keep digging.

**Comment by ArtPoon** [comment] 2017-12-16 00:50
Thanks for the informative posting. There is not a standard procedure for encoding an amino acid position with an “X”, which indicates ambiguity.  When there are more than two or three amino acids in a list, that tells me there is more than one uncertain nucleotide. It may be that sierrypy or the HIVdb webserver has a cutoff on the number of amino acids in a list.  

For the time being, I would parse the discordant cases and try to reverse engineer a rule set for classifying an amino acid as X based in the list input

**Comment by ArtPoon** [comment] 2018-02-01 20:49
Duplicate of #11 
Close but we can refer to the data above

**Closed by ArtPoon** 2018-02-01 20:49 UTC
