### ISSUE TITLE
NRTI resistance profile

### ISSUE THREAD

**Issue by Kanyerezi30** [PoonLab/sierra-local#99] opened 2024-01-19 07:49 UTC
Hello

I am seeing a difference in the resistance profiles assigned by sierra-local and stanford among the NRTI drugs. Is their any possible explanation. Below is the consensus fasta

`>HIV1234
CCTCAAATCACTCTTTGGCAACGACCCCTTGTTACAGTAAAGATAGGGGGACAGCTAAAAGAAGCTCTATTAGATACAGGAGCAGATGATACAGTATTAGAAGACATAAATTTGCCAGGAAAATGGAAACCAAAAATGATAGGGGGAATTGGAGGTTTTATCAAAGTAAAGCAATATGAACAGATACCTATAGAAATTTGTGGAAAAAAGGCTATAGGTACAGTRTTAGTAGGACCTACACCTGYCAACATAATTGGAAGAAATMTTCTGACCCAAATTGGTTGTACTTTAAATTTCCCAATTAGTCCTATTGATACTGTACCAGTTAAATTAAAGCCAGGAATGGATGGCCCAAGGGTTAAACAATGGCCATTAACAGAAGAAAAAATAAAGGCATTAACAGAAATTTGTGCAGAGTTGGAAAAGGATGGAAAAATTTCAAAAATTGGGCCTGAAAATCCATACAATACTCCAATATTTGCTATAAAGAAGAAAAACAGCACTAAATGGAGAAAATTAGTAGATTTCAGAGAGCTTAATAAAAGAACTCAAGATTTTTGGGAAGTTCAATTAGGAATACCGCATCCAGCGGGCTTACCAAAGAAAAAATCAGTAACAGTACTAGATATAGGGGATGCATATTTTTCAGTTCCCTTAGATGAAAGCTTTAGGAAGTATACTGCTTTCACCATACCTAGTACAAACAATGCCACACCAGGAATCAGGTACCAGTACAATGTACTTCCACAGGGATGGAAGGGATCACCAGCAATATTCCAGTGTAGCATGATAAAAGTCCTAGAGCCCTTTAGAGCAMAGAATCCAGAAATAATCCTCTATCAATACGTGGATGACTTGCTTGTAGGGTCTGATTTAGAAATAGGGCAGCATAGAGCAAAAGTAGAAGAnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnCACACCAGACAACAAGCATCAGAAAGAGCCGCCATTTCTTTGGATGGGTTATGAACTCCATCCTGACAAGTGGACAGTCCAGCCTATAAAGCTGCCAGAAAAAGACAGCTGGACTGTCAATGAYATACAGAAATTAGTAGGAAAACTAAATTGGGCAAGTCAAATTTATCAAGGAATTAAGGTAAnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnGAATTGGCAGAGAACAGGGAGATTCTAAAAGACCCTGTGCATGGGGTATACTATGATCCATCAAAAGACTTAATAGCAGAAATACAAAAGCAAGGACAAGACCAATGGACATATCAAGTTTATCAAGAGCCATTTAAAAATCTGAAAACAGGAAAATATGCAAGACAAAGGTCTGCTCACACTAATGATGTAAAACAATTAACAGAAGTAGTGCAGAAGGTAGCCATGGAAAGCATAGTAATATGGGGAGAGACTCCTAAATTTAAATTACCCATACAAAAGGAAACATGGGAAACATGGTGGAGGGACTATTGGCAGGCTACCTGGATTCCTGAATGGGAGTTTGTCAATACCCCCCCTCTAGTAAAATTATGGTACCAATTAGAAAAAGACCCCATAATAGGAGCTGAGACTTTCTATGTAGATGGGGCAGCCAATAGGGAGACTAAGCTAGGAAAAGCAGGGTATGTCACTGACAGAGGAAGACAAAAAGTTGTCTCCATAACTGAGACAAnAAATCAAAAAACTGAATTACATGCAGTTTATCTTGCCCTGCAGGATTCAGGATCACAAGTAAACATAGTAACAGACTCACAGTATGCATTAGGAATAATTCAGGCTCAACCAGATAGGAGTGAATCAGAGTTAGTCAATCACATAATAGAAAAGCTAATAGAAAAGGACAAAGTCTACCTGTCATGG`

**Comment by WilliamZekaiWang** [comment] 2024-01-19 18:17
Hi, I've reproduced the issue.

Looking over the output file, it seems we are reporting mutations that sierrapy isn't reporting causing an incorrect report for NTRI drugs. I suspect this may be similar to #72 due to the `n` nucleotides within the sequence. 

I can look deeper into this

**Comment by WilliamZekaiWang** [comment] 2024-01-29 19:42
I think I have fixed the issue. 

In #72 I made it so it only ignored positions that have all 3 NTs as `NNN`. I have updated the script such that, if it's reported as X for amino acid, it ignores it in score calculation

Additionally, I found a bug in #98 that resulted in miscalculating the score after adjusting for ambiguous positions and have fixed it.

**Comment by ArtPoon** [comment] 2024-01-30 14:22
Fixed with PR #100

**Closed by ArtPoon** 2024-01-30 14:22 UTC
