### ISSUE TITLE
Alignment Program

### ISSUE THREAD

**Issue by Kanyerezi30** [PoonLab/sierra-local#71] opened 2023-01-18 06:44 UTC
Hello here,
From the Stanford University HIV Drug Resistance Database (HIVdb) Sierra web service, looks like the alignment program was changed from NucAmino to PostAlign (Version 3.2 update 2022-07-06). Is there a way of implementing this in the sierra-local and does it impact the final results. Below is the link to the sources of the updates

[https://hivdb.stanford.edu/page/program-updates/#version.2.2.0.update.2017-12-18.code.name.nucamino.](sierra program updates)

**Comment by ArtPoon** [comment] 2023-01-19 02:52
Hi @Kanyerezi30 - thanks for the heads up.  We will investigate.  This might explain some other issues we're working on.

**Comment by ArtPoon** [comment] 2023-01-31 14:25
Getting postalign working will probably resolve #69 but it is not clear how to get this program to work (need documentation)

**Comment by ArtPoon** [comment] 2023-01-31 15:25
@GopiGugan @WilliamZekaiWang - I think we can get some idea of how to run postalign from this excerpt:
https://github.com/hivdb/sierra-core/blob/df95732512776ff5269b192a4592f89b97480f71/src/main/java/edu/stanford/hivdb/sequences/PostAlignAligner.java#L152-L185

**Comment by WilliamZekaiWang** [comment] 2023-03-05 03:42
Seems like the issue with running post align might come from not having `cython` version 0.29.32 and/or python3 version 3.9. I'll look into this and see if this might be the cause why

**Comment by ArtPoon** [comment] 2023-03-05 17:33
Safest way to go about this is to build a virtual environment with the specific versions of Python and modules.  Let me know if you need a hand with setting this up.

**Comment by ArtPoon** [comment] 2023-03-07 14:22
@WilliamZekaiWang reports that he was able to run postalign, we may need to increase our version requirement for Python to 3.9

**Comment by ArtPoon** [comment] 2023-03-07 14:22
We'll need to write a wrapper function for postalign in Python

**Comment by ArtPoon** [comment] 2023-03-07 14:25
since postalign seems to be a proper Python module, however, we could just import it and direct call its functions within the script

**Comment by ArtPoon** [comment] 2023-03-14 13:30
@GopiGugan has postalign running on the terminal but it is hanging (may be waiting for expected input from stdin?)
@WilliamZekaiWang was only able to run postalign within Python but not on terminal - need to compare differences in system configs with Gopi

**Comment by ArtPoon** [comment] 2023-03-28 13:29
@WilliamZekaiWang can you please update this issue with the current results from running postalign?

**Comment by WilliamZekaiWang** [comment] 2023-04-02 02:54
I did more testing with postalign and found it could solve issue #69. Using the incorrectly aligned sequences with postalign and comparing it to sierrapy, the total aligned nucleotide count matched with both sequences.

In terms of issue #65 postalign doesn't exactly solve it
This is sierrapy mutations field:
```
          {
            "consensus": "V",
            "position": 35,
            "AAs": "M",
            "isInsertion": false,
            "isDeletion": false,
            "isApobecMutation": false,
            "isApobecDRM": false,
            "isUnusual": false,
            "isSDRM": false,
            "hasStop": false,
            "primaryType": "Other",
            "text": "V35M"
          }
```

and this is postalign's output:
```
            {
              "Position": 35,
              "RefCodonText": "GTA",
              "CodonText": "ATG",
              "RefAminoAcidText": "V",
              "AminoAcidText": "M",
              "InsertedCodonsText": "",
              "IsInsertion": false,
              "IsDeletion": false
            }
```

However, given that they provide the position, codon, and amino acid, I can port over the outputs I've created from nucamino to postalign for the missing fields

**Comment by WilliamZekaiWang** [comment] 2023-05-08 18:15
ran into another issue where calling postalign using a subprocess and the sequence:
```
>AF227710.JF02-8w.B.80
GGGATGGATGGCCCAAGAGTTAAACAATGGCCATTAACAGAAGAAAAAATAAAAGCATTAATAGAAATTTGTACAGAATTGGAAGAGGAAGGAAAAATTACAAAAATTGGGMMTGAAAATMMATACAATACTMCAGTATTTGCCATAAAGAAGAAA...AGTGGTAGATGGAGAAAAATARCAGATTTCAGAGAACTTAATAAGAGAACTCAAGACTTCTGGGAAGTCCAATTAGGAATACCACATCCTGGAGGGTTAAAAAAGAAYAAATCAGTAACAGTACTGGATGTGGGTGATGCATATTTCTCAGTTCCCTTAGATGAAGACTTCAGGAAGTACACTGCATTTACCATACCTAGTATGAACAATGAGACACCAGGGATTAGATATCAGTACAATGTGCTWCCACAGGGATGGAAAGGATCACCAGCAATATTCCAAAGTAGCATGACAAAAATCTTAGAGCCTTTTAGAAAACAAAAYCCAGACATAATCATCTATCAATACGTGGATGATTTGTATGTAGGATCTGACTTAGAAATAGAGCAGCATAGAACAAAAATAGAGGAACTGAGACAACATCTGTTGAGGTGGGGATTTTTTACACCAGACCAAAAACATCAGAAAGAACCCCCATTCCATTGGATGGGTTATGAACTCCATCCTGATAAATGGACAGTACAGCCTATAGTGCTGCCAGAAAAAGACAGCTGGACTGTCAATGACATACAGAAGTTAGTGGGAAAATTGAATTGG
```
This would result in a subprocess error: returned non-exit status 1. Not too sure if the issue lies with post-align or the config file, as other sequences in the automatically generated RT file provided no errors

**Comment by WilliamZekaiWang** [comment] 2023-05-08 19:15
the second sequence there is also one of the sequences that nucAmino incorrectly gives the NA sequence for listed in #69

**Comment by ArtPoon** [comment] 2023-05-09 13:19
Try re-running these two sequences with all `.` characters removed, to see if we still get the same error

**Comment by WilliamZekaiWang** [comment] 2023-05-12 15:42
The error above is fixed by removing all illegal characters.

**Comment by WilliamZekaiWang** [comment] 2023-05-12 15:45
The mutation position for postalign seem to be consistently 1 lower than that of sierrapy

post:
```
"mutations": [
          {
            "consensus": "V",
            "position": 34,
            "AAs": "T",
            "isInsertion": false,
            "isDeletion": false,
            "isApobecDRM": false
          },
          {
            "consensus": "E",
            "position": 35,
            "AAs": "A",
            "isInsertion": false,
            "isDeletion": false,
            "isApobecDRM": false
          },
```

sierrapy
```
        "mutations": [
          {
            "consensus": "V",
            "position": 35,
            "AAs": "T",
            "isInsertion": false,
            "isDeletion": false,
            "isApobecMutation": false,
            "isApobecDRM": false,
            "isUnusual": false,
            "isSDRM": false,
            "hasStop": false,
            "primaryType": "Other",
            "text": "V35T"
          },
          {
            "consensus": "E",
            "position": 36,
            "AAs": "A",
            "isInsertion": false,
            "isDeletion": false,
            "isApobecMutation": false,
            "isApobecDRM": false,
            "isUnusual": false,
            "isSDRM": false,
            "hasStop": false,
            "primaryType": "Other",
            "text": "E36A"
          },
```

**Comment by ArtPoon** [comment] 2023-05-16 13:24
This is probably a Python 0-index issue (coordinates are being reported in 1-index)

**Comment by WilliamZekaiWang** [comment] 2023-05-19 18:51
seems like I was using an old csv file to detect `isSDRM`. I found a newer file on Hivdb/facts and it fixed nearly all the issues. The `isApobecMutation` seemed to be an issue with my function; I fixed it and the majority of the misreports were fixed.

The remaining errors, 14 to be exact, are all from the amino acid being reported as X, as reported in #65

**Closed** 2023-06-06 13:13 UTC
